# Generated by Django 3.0.4 on 2020-04-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=200)),
                ('star_description', models.TextField()),
                ('star_image', models.ImageField(upload_to='')),
                ('star_cost', models.BigIntegerField()),
                ('star_type', models.CharField(max_length=200)),
                ('star_position', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
