# Generated by Django 3.0.4 on 2020-05-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20200430_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star_image',
            field=models.ImageField(upload_to='media/static'),
        ),
    ]
