# Generated by Django 3.0.4 on 2020-05-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20200502_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star_image',
            field=models.ImageField(upload_to='showcase/static'),
        ),
    ]
